on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '1.23'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: make build
    - name: Archive Binaries Individually
      run: |
          mkdir -p release;
          for b in bin/*; do
            name=$(basename "$b")
            echo "Archiving $name..."
            zip -j "release/${name}.zip" "$b"
          done
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: release/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: release

      - name: Create GitHub Release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: release/*
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
  

          
          
